version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:10.15.0"
    environment:
      DATABASE_URL: postgresql://root@localhost/circle_test
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm i -g npm@latest
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          command: |
            mkdir -p ~/reports
            npm run lint
          name: Lint
          when: always
      - run:
          command: |
            mkdir -p ~/reports
            npm run test
          name: Test
          when: always
      # - run:
      #     name: Generate Code Coverage
      #     command: nyc report --reporter=text-lcov
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
workflows:
  version: 2
  test:
    jobs:
      - build