version: 1
jobs:
  test:
    environment:
      DATABASE_URL: postgresql://root@localhost/circle_test
    branches:
      only:
        - master
    steps:
      - run:
          command: npm run test
          name: Test
          when: always