version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:10.15.0"
    environment:
      DATABASE_URL: postgresql://root@localhost/circle_test
    steps:
      - run:
          command: npm run test
          name: Test
          when: always

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only: dev