version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:10.15.0"
    environment:
      DATABASE_URL: postgresql://root@localhost/circle_test
    working_directory: ~/Gaijin
    steps:
      - run:
          command: |
            npm i eslint -D
            mkdir -p ~/reports
            eslint ./src/ --format junit --output-file ~/reports/eslint.xml
          name: Lint
          when: always
      - run:
          command: |
            npm i ava -D
            npm i nyc -D
            mkdir -p ~/reports
            npm run test
          name: Test
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only: dev